# Generated by Django 5.2.6 on 2026-05-24 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_as_client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="services.servicelisting",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["client", "status"], name="idx_client_status"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["service", "status"], name="idx_service_status"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["-scheduled_at"], name="idx_scheduled_desc"),
        ),
    ]
