# Generated by Django 5.2.6 on 2026-05-24 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelisting",
            name="provider",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROVIDER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="servicelisting",
            index=models.Index(
                fields=["provider", "is_active"], name="idx_provider_active"
            ),
        ),
        migrations.AddIndex(
            model_name="servicelisting",
            index=models.Index(
                fields=["category", "is_active"], name="idx_category_active"
            ),
        ),
        migrations.AddIndex(
            model_name="servicelisting",
            index=models.Index(
                fields=["service_area", "is_active"], name="idx_area_active"
            ),
        ),
        migrations.AddIndex(
            model_name="servicelisting",
            index=models.Index(fields=["-created_at"], name="idx_created_desc"),
        ),
    ]
